name: glog publish

on:
  schedule:
    - cron: '0 0 1 1-12 *'
  push:
    branches:
      - main

jobs:
  build:
    env:
      GIT_REPO_STATS_READ_TOKEN_FOR_GATSBY: ${{ secrets.GIT_REPO_STATS_READ_TOKEN_FOR_GATSBY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GIT_REPO_STATS_READ_TOKEN_FOR_GATSBY }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
